name: parent_gp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.4+1
  firebase_core : ^0.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "images/1.jpeg"



flutter:

  
  uses-material-design: true


  assets:
    - images/1.jpeg
    - images/10.jpeg
    - images/3.png
    - images/g.png
    - images/f.png
    - images/boy.jpeg
    - images/girl.jpeg
    
  